#include "../../helpers.ligo"
#define CALLBACK
#import  "../../partial/parser/errors.ligo" "Errors"
#include "../../partial/parser/storage.ligo"
#include "../../partial/parser/helpers.ligo"
#include "../../partial/parser/methods.ligo"
#import "../../partial/parser/vendor/ctez/constants.ligo" "Constants"
#include "../../partial/parser/vendor/ctez/types.ligo"
#include "../../partial/parser/vendor/ctez/methods.ligo"
#include "../../partial/parser/main.ligo"
