#include "../../helpers.ligo"
#define CALLBACK
#import  "../../partial/parser/errors.ligo" "Errors"
#include "../../partial/parser/storage.ligo"
#include "../../partial/parser/helpers.ligo"
#include "../../partial/parser/methods.ligo"
#import "../../partial/parser/vendor/ubinetic/sirs_lp/constants.ligo" "Constants"
#include "../../partial/parser/vendor/ubinetic/sirs_lp/types.ligo"
#include "../../partial/parser/vendor/ubinetic/sirs_lp/methods.ligo"
#include "../../partial/parser/main.ligo"