#include "../../helpers.ligo"
#import  "../../partial/parser/errors.ligo" "Errors"
#include "../../partial/parser/storage.ligo"
#include "../../partial/parser/helpers.ligo"
#include "../../partial/parser/methods.ligo"
#import "../../partial/parser/vendor/wtez/constants.ligo" "Constants"
#include "../../partial/parser/vendor/wtez/methods.ligo"
#include "../../partial/parser/main.ligo"
